# Generated by Django 2.0.4 on 2018-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
