# Generated by Django 2.0.4 on 2018-07-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_members_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=150)),
                ('ev_name', models.CharField(blank=True, max_length=500)),
                ('college_name', models.CharField(max_length=10)),
                ('fest_name', models.CharField(blank=True, max_length=100)),
                ('ev_date', models.DateField()),
                ('photos', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500)),
                ('ev_type', models.CharField(max_length=10)),
                ('ev_date', models.DateField()),
                ('event_head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500)),
                ('ev_type', models.CharField(max_length=10)),
                ('ev_date', models.DateField()),
                ('event_head', models.CharField(max_length=100)),
                ('photos', models.URLField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(max_length=500)),
                ('imag', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('developed', models.BooleanField(default=True)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=100)),
                ('photos', models.URLField(blank=True, null=True)),
                ('url_code', models.URLField(blank=True, null=True)),
                ('url_project', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500)),
                ('ev_type', models.CharField(max_length=10)),
                ('ev_date', models.DateField()),
                ('event_head', models.CharField(max_length=100)),
                ('poster', models.URLField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
