# Generated by Django 2.0.4 on 2018-07-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180801_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
    ]
