# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='did_by',
            field=models.ManyToManyField(to='portalapp.ACEUserProfile'),
        ),
    ]
