# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_tasks_did_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='did_by',
            field=models.ManyToManyField(blank=True, null=True, to='portalapp.ACEUserProfile'),
        ),
    ]
