# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portalapp', '0004_aceuserprofile_task_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aceuserprofile',
            unique_together=set([('name', 'enroll_number', 'email_id', 'task_submitted')]),
        ),
    ]
