# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0007_auto_20170806_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceuserprofile',
            name='section',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
