# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0009_auto_20170806_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceuserprofile',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
