# Generated by Django 2.1 on 2018-08-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aceuserprofile',
            unique_together={('email_id', 'task_id')},
        ),
    ]
