# Generated by Django 2.1 on 2018-08-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_auto_20180815_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='did_by',
        ),
        migrations.AlterUniqueTogether(
            name='aceuserprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submissions',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Tasks'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.ACEUserProfile'),
        ),
        migrations.RemoveField(
            model_name='aceuserprofile',
            name='task_id',
        ),
        migrations.AlterUniqueTogether(
            name='submissions',
            unique_together={('user', 'task')},
        ),
    ]
