# Generated by Django 2.1 on 2018-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_auto_20180815_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceuserprofile',
            name='submission_url',
        ),
        migrations.RemoveField(
            model_name='aceuserprofile',
            name='task_submitted',
        ),
        migrations.AddField(
            model_name='submissions',
            name='submission_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='task_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
