# Generated by Django 2.1.1 on 2018-09-09 19:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_auto_20180815_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceuserprofile',
            name='is_council',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aceuserprofile',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='aceuserprofile',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
