# Generated by Django 2.1.1 on 2018-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_auto_20180909_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceuserprofile',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
