# Generated by Django 2.1.1 on 2018-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0006_auto_20181007_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='submission_deadline',
            field=models.CharField(max_length=10),
        ),
    ]
