# Generated by Django 2.1 on 2018-09-04 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_auto_20180815_0229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_email_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail_ACEUserProfileCoreMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='You can use tags:<br>@username<br>@fullName<br>@firstName<br>@lastName')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('members', models.ManyToManyField(related_name='_sendemail_aceuserprofilecoremembers_members_+', to='portalapp.ACEUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail_ACEUserProfileMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='You can use tags:<br>@username<br>@fullName<br>@firstName<br>@lastName')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('members', models.ManyToManyField(related_name='_sendemail_aceuserprofilemembers_members_+', to='portalapp.ACEUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SendEmail_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='You can use tags:<br>@username<br>@fullName<br>@firstName<br>@lastName')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('users', models.ManyToManyField(related_name='_sendemail_user_users_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='users',
        ),
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
