# Generated by Django 2.1.1 on 2018-09-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_email_sender', '0003_auto_20180904_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemail_aceuserprofile',
            options={'verbose_name': 'Email ACE Member'},
        ),
        migrations.AlterModelOptions(
            name='sendemail_aceuserprofilecore',
            options={'verbose_name': 'Email ACE Core Member'},
        ),
        migrations.AlterModelOptions(
            name='sendemail_user',
            options={'verbose_name': 'Email all User'},
        ),
    ]
